"""tambah tabel tim_akses

Revision ID: 38cfcfbbbba2
Revises: a0e8490ee914
Create Date: 2026-04-30 21:00:36.172872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38cfcfbbbba2'
down_revision = 'a0e8490ee914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tim_akses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('akses_crud', sa.Boolean(), nullable=True),
    sa.Column('diberikan_oleh', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diberikan_oleh'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tim_akses')
    # ### end Alembic commands ###
