"""add tanggal_pelaksanaan to program

Revision ID: 8a8f41637a3a
Revises: b6177e1a0c2d
Create Date: 2026-05-24 10:01:33.324757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a8f41637a3a'
down_revision = 'b6177e1a0c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanggal_pelaksanaan', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.drop_column('tanggal_pelaksanaan')

    # ### end Alembic commands ###
