"""tambah lokasi dan jumlah_relawan ke program

Revision ID: a0e8490ee914
Revises: f86500e84dd5
Create Date: 2026-04-30 13:50:52.644071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e8490ee914'
down_revision = 'f86500e84dd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lokasi', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('jumlah_relawan', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.drop_column('jumlah_relawan')
        batch_op.drop_column('lokasi')

    # ### end Alembic commands ###
