"""face_encoding

Revision ID: febd01db46b1
Revises: 38cfcfbbbba2
Create Date: 2026-05-05 12:53:52.537457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'febd01db46b1'
down_revision = '38cfcfbbbba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_encoding', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('face_encoding')

    # ### end Alembic commands ###
